### ISSUE TITLE
Sugestão de Melhoria

### ISSUE THREAD

**Issue by igorbrandao** [rhuankarlus/arduino#1]
Funções de desligamento, pausa na leitura e update manual da temperatura (ambos mediante pressionamento de botão) poderiam ser implementadas para melhorar as funcionalidades do dispositivo.

Esboço de desligamento:

    void loop(void) {
        delay(1000);
        lerTemperaturaEUmidade();
        escreverTemperaturaEUmidadeNoLCD();
        if(buttonEntity.shutdownPressed()) ){
            // break outter loop
        }
    }

Esboço de pausa:

    boolean pausa = false;
    void loop(void) {
        delay(1000);
        lerTemperaturaEUmidade();
        escreverTemperaturaEUmidadeNoLCD();
        if(buttonEntity.pausePressed()) {
            pausa = true;
            while(pausa) {
                delay(100);
                if(buttonEntity.buttonPressed()) {
                    pausa = false;
                }
            }
        }
    }

Esboço de update manual:

    void loop(void) {
        delay(1000);
        lerTemperaturaEUmidade();
        escreverTemperaturaEUmidadeNoLCD();
        if(buttonEntity.pausePressed()) {
            pausa = true;
            while(pausa) {
                delay(100);
                if(buttonEntity.updatePressed()) ){
                    //call update function
                }
                if(buttonEntity.buttonPressed()) {
                    pausa = false;
                }
            }
        }
    }

**Comment by rhuankarlus** [comment]
Feito: O LCD fica desligado e a temperatura e a umidade só são lidas a partir do pressionamento de um botão. A duração da visualização é de cinco segundos, não é necessário mais que isso. Depois de cinco segundos o LCD se desliga.
